### ISSUE TITLE
level.blind / smartVISU

### ISSUE THREAD

**Issue by vova7788** [Jey-Cee/ioBroker.heytech#19]
Hi,

Frage Nr.1:
Verstehe ich es richtig, dass beim Ändern des Wertes „level.blind“ von 0 bis 100 dürfen die Rollladen, unabhängig davon auf welchen Position diese gerade sich befinden, auf eine entsprechende Position fahren? Wenn es so ist, dann dürfte bei mir etwas falsch laufen:

1.	Rollo oben (Endposition) - Angabe z.B. 50% - keine Bewegung
2.	Rollo ist irgendwo (nicht Endposition oben) - Angabe 30% oder 70% - fahren ganz hoch in Endposition
Also Reaktion auf Ändern des Wertes nur im Falle, wenn Rollo sich nicht in obere Endpositon befindet.

Frage Nr.2:
Haben die Einstellungen in der Rolladensteuerung beim Bedienen z.B. durch Instanzen/Objekten in iobroker eine Auswirkung oder sind nur für manuelle (Schalter im Haus) Steuerung relevant?

Frage Nr.3:
Ich beschäftige mich seit Kurzem mit smartVISU (smartvisu.de). Es scheint mir etwas leichter zu verstehen und bedienen (Projektaufbau)
Da gibt es sehr interessante und meiner Meinung nach sehr flexible/universelle Rolladensteuerung.
Hier ist die Beschreibung von Parameter für Device-Widgets:
https://docu.smartvisu.de/2.9/index.php?page=device/widget_device.shutter

Nur das Problem ist, dass die entsprechenden Parameter bzw. in iobroker Objekte fehlen.

Parameter in smartVISU:

{{ device.shutter(id, txt, item_move, item_stop, item_pos, item_shift, item_angle, item_saved, value_top, value_bottom, step, mode, background, value_pos_1, value_pos_2, text_pos_1, text_pos_2) }}

id 
unique id for this widget (optional)
txt 
name of the shutter
item_move 
an item for the up and down movement (optional, value_top/value_bottom will be sent to item_pos if omitted)
item_stop 
an item for stopping the movement (optional)
item_pos 
an item for the absolute position of the blinds
item_shift 
an item for increase and decrease of the blade (optional, for future use)
item_angle 
an item for the absolute angle of the blade (optional)
item_saved 
an item for some saved positions (optional)
value_top 
the value for opened (optional, default 0)
value_bottom 
the value for closed (optional, default 255)
step 
step between two values (optional, default 5)
mode 
'half' blade turns from -1 to +1, 'full' blade turns from 0 to +1 (optional, default 'half')
background 
a background image url (relative to smartVISU directory or absolute); optimal size is 100px x 180px (optional)
value_pos_1 
the value to send for position 1 (optional, default 0)
value_pos_2 
the value to send for position 2 (optional, default 1)
text_pos_1 
the text printed on button for position 1 (optional, default Pos1)
text_pos_2 
the text printed on button for position 2 (optional, default Pos2)

Ich kann nur folgende Parameter benutzen, da in iobroker nur diese Objekte existieren

**Beispil für Rollo „heytech.0.shutters.22“**
id  - heytech.0.shutters.22
item_stop - heytech.0.shutters.22.stop
item_pos  - heytech.0.shutters.22.percent (funktioniert aber nicht richtig. In Frage 1 beschrieben)

die Parameter werden in iobroker über socketio.0 übermittelt und gut angenommen:

Log:

heytech.0 | 2020-08-14 08:47:41.252 | info | (14052) Disconnected from   controller
-- | -- | -- | --
heytech.0 | 2020-08-14 08:46:42.681 | info | (14052) stop 22
heytech.0 | 2020-08-14 08:46:41.247 | info | (14052) down 22
heytech.0 | 2020-08-14 08:46:39.367 | info | (14052) stop 22
heytech.0 | 2020-08-14 08:46:35.755 | info | (14052) Connected to controller
heytech.0 | 2020-08-14 08:46:35.754 | info | (14052) down 22
socketio.0 | 2020-08-14 08:46:27.760 | info | (7948) ==>Connected   system.user.admin from ::ffff:192.168.178.51
socketio.0 | 2020-08-14 08:46:27.167 | info | (7948) <==Disconnect   system.user.admin from ::ffff:192.168.178.51 smartVISU

Ist es möglich für fehlende Parameter die entsprechenden Objekte in iobroker zu erzeugen?

Heytech Rolladensteuereung (WS879M + 2 Extension-Modulen). Firmware: V.8.027o

**Comment by Jey-Cee** [comment]
Ich hab keine Heytech Steuerung und nur die Basis des Adapters gebaut, deshalb kann ich zu Frage 2 gar nichts sagen.

Zu 1. kann ich sagen das die Angabe tatsächlich in % von 0 bis 100 gehen sollte. 

Zu 3. 
> Ist es möglich für fehlende Parameter die entsprechenden Objekte in iobroker zu erzeugen?
Ja du musst dir die entsprechenden Objekte in 0_userdata anlegen und mit einem Skript dann umbiegen.

Vielleicht kann @ansgarschulte noch mehr dazu sagen er hat einen großteil des Adapters geschrieben und auch die Hardware.

**Comment by ansgarschulte** [comment]
Hi
Schaue ich mir mal an. Schaffe ich aber erst Anfang der Woche.

**Comment by ansgarschulte** [comment]
Ich glaube deine Firmware ist zu alt.

**Comment by ansgarschulte** [comment]
Ich habe damals von Herrn Hey die Firmware: V.8.027p_beta bekommen, damit die prozentuale Ansteuerung funktioniert

**Comment by ansgarschulte** [comment]
zu Frage 2:  Was meinst du genau? Die Einstellungen des Adapters betreffen nur ioBroker. Es werden keine Änderungen am Modul durch den Adapter ausgeführt. Die einzige Beeinträchtigung ist, dass der Telnet Port vom ioBroker regelmäßig blockiert wird und somit ein Zugriff über HeyControl oder die Hey App nicht möglich ist. Dazu muss man das Aktualisierungsintervall des Adapters hochsetzen oder die Adapter Instanz pausieren.

**Comment by ansgarschulte** [comment]
Zu Frage 3:
welche fehlen denn genau?
Also bei jeder Shutter gibt es 5 Obejekte:

- heytech.0.shutters.10.down --> komplett auf
- heytech.0.shutters.10.percent --> setze auf z.b. auf 35%
- heytech.0.shutters.10.status --> aktuell ist der Shutter z.b. zu 67% geöffnet
- heytech.0.shutters.10.stop --> stoppt den fahrenden Shutter
- heytech.0.shutters.10.up --> komplett zu

**Comment by vova7788** [comment]
nach Firmware - Aktualisierung (V.8.027q) funktioniert es! Vielen Dank!!!

**Comment by ansgarschulte** [comment]
> nach Firmware - Aktualisierung (V.8.027q) funktioniert es! Vielen Dank!!!

Oh. Neuere Version! Wie ist denn der Download Link? :-)

**Comment by ansgarschulte** [comment]
Ok selbst gefunden. :-)
https://rolladensteuerung.de/download/firmware/modulsteuerungen/v8.027.zip

**Comment by ansgarschulte** [comment]
Wenn noch fragen sind: Reopen issue
